version: '3.5'

networks: 
    kong-net:
        name: kong-net
        ipam: 
            config: 
                - subnet: 172.20.10.0/24

services: 
    db:
        container_name: postgres-db
        image: postgres:9.6
        environment: 
            POSTGRES_USER: kong
            POSTGRES_PASSWORD: kong
            POSTGRES_DB: kong
        networks:
            - kong-net
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "kong"]
            interval: 10s
            timeout: 10s
            retries: 3
    adminer:
        container_name: adminer
        image: adminer:4.7.3-standalone
        ports:
        - 8080:8080
        networks: 
            - kong-net