version: '3.5'

networks: 
    kong-net:
        external: true

services:
    kong:
        image: kong:latest
        container_name: kong-gateway
        environment: 
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: '0.0.0.0:8001'
            KONG_DATABASE: postgres
            KONG_PG_DATABASE: kong
            KONG_PG_HOST: db
            KONG_PG_PASSWORD: kong
            KONG_PG_USER: kong
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
        networks: 
            - kong-net
        ports: 
            - 8000:8000
            - 8001:8001
            - 8443:8443
            - 8444:8444
    konga:
        container_name: kong-gui
        image: pantsel/konga:latest
        ports: 
            - 1337:1337
        networks: 
            - kong-net
        environment: 
            NODE_ENV: production
            TOKEN_SECRET: loli-savior
            DB_ADAPTER: postgres
            DB_HOST: db
            DB_USER: kong
            DB_PASSWORD: kong
            DB_DATABASE: konga_db